# Table Ausentismo

In [60]:
import pandas as pd
data=pd.read_csv("elecciones_limpio.csv")

In [61]:
# Filtrar las filas donde 'Año' es igual a 2022
data = data[data["Año"] == 2022]

data

,Region,Provincia,Distrito,Ubigeo,Votosemitidos,Electores,N_Partidos,P_ausentismo,Año
0,AMAZONAS,CHACHAPOYAS,ASUNCION,10102,267.0,170.0,2.0,0.392647,2022
1,AMAZONAS,CHACHAPOYAS,BALSAS,10103,538.0,264.0,4.0,0.127044,2022
2,AMAZONAS,CHACHAPOYAS,BALSAS,10103,538.0,265.0,4.0,0.127044,2022
3,AMAZONAS,CHACHAPOYAS,CHETO,10104,514.0,214.0,3.0,0.266046,2022
4,AMAZONAS,CHACHAPOYAS,CHETO,10104,514.0,215.0,3.0,0.266046,2022
...,...,...,...,...,...,...,...,...,...
6330,UCAYALI,ATALAYA,TAHUANIA,250302,2468.0,230.0,6.0,0.057638,2022
6331,UCAYALI,ATALAYA,TAHUANIA,250302,2468.0,286.0,6.0,0.057638,2022
6332,UCAYALI,ATALAYA,TAHUANIA,250302,2468.0,287.0,6.0,0.057638,2022
6333,UCAYALI,ATALAYA,YURUA,250303,672.0,238.0,6.0,0.077634,2022
6334,PIURA,MORROPON,SANTO DOMINGO,190407,4010.0,199.0,4.0,0.161119,2022

In [62]:
data = data.drop_duplicates()

In [63]:
# Crear una copia del DataFrame excluyendo la columna "Electores" para identificar duplicados
data= data.drop(columns=["Electores"])

# Identificar los índices de las filas duplicadas
duplicados = data.duplicated(keep='first')

# Eliminar las filas duplicadas basándonos en todas las columnas excepto "Electores"
data = data[~duplicados]

In [67]:
# Crear la variable nivel_ausentismo con nuevas reglas
def clasificar_ausentismo(valor):
    if valor > 0.30:
        return "3_Alto"
    elif valor >= 0.20:
        return "2_Alerta"
    else:
        return "1_Bajo"

data['nivel_ausentismo'] = data['P_ausentismo'].apply(clasificar_ausentismo)

# Verificar los niveles creados
print(data['nivel_ausentismo'].value_counts())

nivel_ausentismo
1_Bajo      1385
2_Alerta     233
3_Alto        76
Name: count, dtype: int64

In [65]:
# Ver valores únicos en la columna 'nivel_ausentismo'
print(data['nivel_ausentismo'].unique())

# Ver distribución de datos dentro de cada nivel
for nivel in data['nivel_ausentismo'].unique():
    print(f"\nValores para el nivel {nivel}:")
    print(data[data['nivel_ausentismo'] == nivel]['P_ausentismo'].describe())

['3_Alto' '1_Bajo' '2_Medio']

Valores para el nivel 3_Alto:
count    76.000000
mean      0.367074
std       0.048292
min       0.300412
25%       0.337093
50%       0.358841
75%       0.388208
max       0.553986
Name: P_ausentismo, dtype: float64

Valores para el nivel 1_Bajo:
count    1385.000000
mean        0.125235
std         0.039035
min         0.000000
25%         0.095068
50%         0.124058
75%         0.155863
max         0.199920
Name: P_ausentismo, dtype: float64

Valores para el nivel 2_Medio:
count    233.000000
mean       0.238113
std        0.021799
min        0.200118
25%        0.221331
50%        0.239550
75%        0.254375
max        0.293016
Name: P_ausentismo, dtype: float64

In [66]:
data["nivel_ausentismo"].value_counts()

nivel_ausentismo
1_Bajo     1385
2_Medio     233
3_Alto       76
Name: count, dtype: int64